project:
  type: website

website:
  title: "Pedro Camões"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - teaching.qmd
      - research.qmd
      - other.qmd
      - about.qmd

format:
  html:
    theme: [brand]
    css: styles.css
    toc: true



